### ISSUE TITLE
How to use android PCS(Private compute service) as client with FCP?

### ISSUE THREAD

**Issue by ganeshShindeQ** [google/federated-compute#10]
How to combine PCS (Private-compute-services) and FCP effectively for federated learning and analytics? could you please share any helpful blogs or resources on this topic?

**Comment by timonvo** [comment]
We currently don't have detailed instructions for combining the two projects into complete system, and it's not something we're pursuing right now. However, you might be able to get some useful information from some of our papers, such as [Towards Federated Learning at Scale: System Design](https://arxiv.org/abs/1902.01046).
