### ISSUE TITLE
`bazel build //fcp/artifact_building:federated_compute_plan_builder` fails with compile error

### ISSUE THREAD

**Issue by yuangu002** [google/federated-compute#12]
Following the GETTING_STARTED guide, I successfully installed all dependencies in `requirements.txt` and verified with `python3 -c "import tensorflow_federated"`:
```
2023-10-20 23:47:49.801507: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-20 23:47:49.862608: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-10-20 23:47:49.863466: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-20 23:47:51.225016: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
```
Then, I run `bazel build //fcp/artifact_building:federated_compute_plan_builder` and got the following build error:
```
INFO: Analyzed target //fcp/artifact_building:federated_compute_plan_builder (181 packages loaded, 15873 targets configured).
INFO: Found 1 target...
ERROR: /usr/local/google/home/ryangu/.cache/bazel/_bazel_ryangu/15955890b671f3e842c09329bd3a9df5/external/org_tensorflow/tensorflow/tsl/lib/io/BUILD:204:11: Compiling tensorflow/tsl/lib/io/cache.cc [for tool] failed: (Exit 1): gcc failed: error executing command (from target @org_tensorflow//tensorflow/tsl/lib/io:cache) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 49 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from external/org_tensorflow/tensorflow/tsl/lib/io/cache.cc:16:
external/org_tensorflow/tensorflow/tsl/lib/io/cache.h:99:11: error: 'uint64_t' does not name a type
   99 |   virtual uint64_t NewId() = 0;
      |           ^~~~~~~~
external/org_tensorflow/tensorflow/tsl/lib/io/cache.h:20:1: note: 'uint64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   19 | #include "tensorflow/tsl/platform/stringpiece.h"
  +++ |+#include <cstdint>
   20 | 
external/org_tensorflow/tensorflow/tsl/lib/io/cache.cc:391:12: error: 'uint64_t tsl::table::{anonymous}::ShardedLRUCache::NewId()' marked 'override', but does not override
  391 |   uint64_t NewId() override {
      |            ^~~~~
Target //fcp/artifact_building:federated_compute_plan_builder failed to build
```

Note:
- Python version: `3.9.17`
- Run at commit: `15379115139fca22e6c2ea1e047826ca2e3f3fa5`

**Comment by timonvo** [comment]
From a quick Google search for that `'uint64_t' does not name a type` error, it looks like this is the same issue as https://github.com/tensorflow/tensorflow/issues/60577, in upstream TensorFlow. It looks like you could try to build with an older version of GCC, or you could try to use Clang instead.

It looks like upstream TF fixed this in https://github.com/tensorflow/tensorflow/pull/61503/commits/055b7147a436360110480ba1ef97f4216e1909d8, but that commit hasn't been released yet, and federated-compute hence isn't using that version of TF yet. We'll pick that fix up in the future when we organically adopt newer TF versions. Until then I recommend trying to use one of the other workarounds, as it's not something we'll be equipped to fix in the federated-compute project, I'm afraid.

**Comment by yuangu002** [comment]
I rollback'ed to `gcc-11` and `gcc-12` and the above error went away, but there are other build errors.

In general, is `clang` better supported than `gcc` in FCP?

**Comment by timonvo** [comment]
We do currently use clang in our testing, so there's more chance that we'll catch issues with it than with GCC. However the versions we test with won't cover all versions of Clang either, and from https://github.com/tensorflow/tensorflow/commit/055b7147a436360110480ba1ef97f4216e1909d8 it seems that at least some newer version of Clang also exhibits this issue. So you might have better luck with clang, but we still can't guarantee that that will always work either.

**Comment by yuangu002** [comment]
This doesn't seem to be a small error. All targets that depend on `//fcp/tensorflow` will get the same error, so I assume it's a more recent release of `clang` breaks the tensorflow build. To solve it, we should either upgrade TF (as you mentioned, FCP hasn't adopted `v2.14.0` yet) or downgrade `clang`.

Since the team tested the repo with `clang` the most, could you share a well-tested `clang` version? I tried `clang-13` to `clang-16` but got no luck on all of them.

**Comment by yuangu002** [comment]
@timonvo so we ended up patching [this fix](https://github.com/tensorflow/tensorflow/commit/055b7147a436360110480ba1ef97f4216e1909d8) on to [`tensorflow 2.13.0`](https://github.com/google/federated-compute/tree/main/fcp/patches), and the target is now able to build.

Let me know if you need me to create a PR.
