### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by doug-leith** [google/federated-compute#3]
When building the compiler exits with error:

In member function 'const void* fcp::aggregation::VectorData<T>::data() const':
./fcp/aggregation/core/vector_data.h:39:52: error: 'const fcp::aggregation::VectorData<T>::vector' has not been declared

full output is:

ERROR: /home/doug/federated-compute/fcp/aggregation/core/BUILD:150:11: Compiling fcp/aggregation/core/federated_sum.cc failed: (Exit 1): gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/a2d1cfe108fb6ecf8584c66084ab27f5/sandbox/processwrapper-sandbox/11649/execroot/com_google_fcp && \
  exec env - \
    PATH=/root/.cache/bazelisk/downloads/bazelbuild/bazel-5.3.0-linux-x86_64/bin:/home/doug/federated-compute/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    TF2_BEHAVIOR=1 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/fcp/aggregation/core/_objs/federated_sum/federated_sum.pic.d '-frandom-seed=bazel-out/k8-opt/bin/fcp/aggregation/core/_objs/federated_sum/federated_sum.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/bin -iquote external/com_google_protobuf -iquote bazel-out/k8-opt/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/k8-opt/bin/external/zlib -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -isystem external/com_google_protobuf/src -isystem bazel-out/k8-opt/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/k8-opt/bin/external/zlib '-std=c++17' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c fcp/aggregation/core/federated_sum.cc -o bazel-out/k8-opt/bin/fcp/aggregation/core/_objs/federated_sum/federated_sum.pic.o)
# Configuration: 049f85fc0d6dedd96dfa70b148f22be32341167164f149dfc9688cc225c2af15
# Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from ./fcp/aggregation/core/agg_vector_aggregator.h:26,
                 from fcp/aggregation/core/federated_sum.cc:20:
./fcp/aggregation/core/vector_data.h: In member function 'const void* fcp::aggregation::VectorData<T>::data() const':
./fcp/aggregation/core/vector_data.h:39:52: error: 'const fcp::aggregation::VectorData<T>::vector' has not been declared
   const void* data() const override { return this->vector::data(); }
                                                    ^~~~~~
Target //fcp/demo:federated_program_test failed to build

**Comment by doug-leith** [comment]
editing file:

fcp/aggregation/core/vector_data.h

and around line 39 changing:

  //const void* data() const override { return this->vector::data(); }
   const void* data() const override { return this->data(); }

seems to fix this.

**Comment by timonvo** [comment]
Thanks for the report. We should be able to land a fix for this soon, I'll mark this fixed when we do.

**Comment by timonvo** [comment]
https://github.com/google/federated-compute/commit/d7f765b57c3295ba43b6a262800fe67691a5d033 should fix this issue. Thanks again for the report!
