### ISSUE TITLE
request: include gRPC demo server

### ISSUE THREAD

**Issue by doug-leith** [google/federated-compute#5]
The demo uses an http federated compute protocol.   There is also a gRPC federated API that the client supports.  It would be good to also include a demo server that supports a gRPC client.

**Comment by timonvo** [comment]
Thanks for the request, but we're actually in the process of migrating to the HTTP-based stack, and plan to turn the gRPC-based stack down eventually. Hence we probably won't be adding support for the gRPC stack to the demo server. I'll close this accordingly.
